### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by lodilorenzo** [alphacep/kaldi-android-demo#19]
Hello,
I'm trying to execute the demo project on Android and after importing it in Android Studio when I try to run it on an emulator the application crashes with this error:

2020-01-08 15:02:44.322 12485-12485/org.kaldi.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.kaldi.demo, PID: 12485
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.kaldi.demo-6-GsN2XIIBXKZfB0d0OXFg==/base.apk"],nativeLibraryDirectories=[/data/app/org.kaldi.demo-6-GsN2XIIBXKZfB0d0OXFg==/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libkaldi_jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at org.kaldi.demo.KaldiActivity.<clinit>(KaldiActivity.java:36)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1243)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3182)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Is there something I can do to resolve this problem?

Thank you very much

**Comment by nshmyrev** [comment]
Update android studio to 64-bit emulator.

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/kaldi-android-demo/issues/6

**Comment by lodilorenzo** [comment]
Thank you I had not seen that issue, I'ts working correctly with 64 bit emulator

**Comment by aleksandrmozgovoi** [comment]
I have the same problem
we use the nox emulator.
Did anyone assemble aar with x86?

**Comment by nshmyrev** [comment]
@aleksandrmozgovoi x86 is now included into kaldi-release aar from github

**Comment by aleksandrmozgovoi** [comment]
> @aleksandrmozgovoi x86 is now included into kaldi-release aar from github

Oh thanks.
