### ISSUE TITLE
different language

### ISSUE THREAD

**Issue by nikosapaster** [alphacep/kaldi-android-demo#32]
Hello I want to ask if kaldi-android demo supports models expect english on any other languages?

**Comment by nshmyrev** [comment]
There are 7 languages already supported available for download in release page:

https://github.com/alphacep/kaldi-android-demo/releases

You can add more, see https://github.com/alphacep/kaldi-android-demo/issues/25

**Comment by nikosapaster** [comment]
I replaced the files that i have created with my training from kaldi..and the logcat gives that:
If you can help with beacuse I am not familiar with these logs.
2020-02-14 12:37:41.208 26325-26346/org.kaldi.demo E/libc++abi: terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError
2020-02-14 12:37:41.208 26325-26346/org.kaldi.demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 26346 (AsyncTask #1), pid 26325 (org.kaldi.demo)
2020-02-14 12:37:41.276 26351-26351/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-02-14 12:37:41.276 26351-26351/? A/DEBUG: Build fingerprint: 'MLS/iQA27X_E_EEA/iQA27X_E:8.1.0/O11019/1542702802:user/release-keys'
2020-02-14 12:37:41.276 26351-26351/? A/DEBUG: Revision: '0'
2020-02-14 12:37:41.276 26351-26351/? A/DEBUG: ABI: 'arm64'
2020-02-14 12:37:41.276 26351-26351/? A/DEBUG: pid: 26325, tid: 26346, name: AsyncTask #1  >>> org.kaldi.demo <<<
2020-02-14 12:37:41.276 26351-26351/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
2020-02-14 12:37:41.280 26351-26351/? A/DEBUG: Abort message: 'terminating with uncaught exception of type kaldi::KaldiFatalError: kaldi::KaldiFatalError'
2020-02-14 12:37:41.281 26351-26351/? A/DEBUG:     x0   0000000000000000  x1   00000000000066ea  x2   0000000000000006  x3   0000000000000008
2020-02-14 12:37:41.281 26351-26351/? A/DEBUG:     x4   fefeff6edfbfa76f  x5   fefeff6edfbfa76f  x6   fefeff6edfbfa76f  x7   7f7f7f7fffffff7f
2020-02-14 12:37:41.281 26351-26351/? A/DEBUG:     x8   0000000000000083  x9   0000000010000000  x10  0000006fe0c0ac40  x11  0000000000000001
2020-02-14 12:37:41.281 26351-26351/? A/DEBUG:     x12  0000000000000018  x13  000000005e467875  x14  000c1f25185a83a2  x15  000050ea3e27772d
2020-02-14 12:37:41.281 26351-26351/? A/DEBUG:     x16  00000064912abfa8  x17  00000070793fd710  x18  0000000000000000  x19  00000000000066d5
2020-02-14 12:37:41.281 26351-26351/? A/DEBUG:     x20  00000000000066ea  x21  0000000000000083  x22  ffffff80ffffffc8  x23  0000006fe0c0ae30
2020-02-14 12:37:41.281 26351-26351/? A/DEBUG:     x24  0000006fe0c0ad10  x25  0000006fe0c0ad50  x26  0000006fe0a53ca8  x27  0000006fe0c0b688
2020-02-14 12:37:41.281 26351-26351/? A/DEBUG:     x28  0000006fe0c0b4c8  x29  0000006fe0c0ac80  x30  00000070793b27e0
2020-02-14 12:37:41.281 26351-26351/? A/DEBUG:     sp   0000006fe0c0ac40  pc   00000070793b2808  pstate 0000000060000000
2020-02-14 12:37:41.291 26351-26351/? A/DEBUG: backtrace:
2020-02-14 12:37:41.291 26351-26351/? A/DEBUG:     #00 pc 000000000001d808  /system/lib64/libc.so (abort+120)
2020-02-14 12:37:41.291 26351-26351/? A/DEBUG:     #01 pc 000000000069b108  /data/app/org.kaldi.demo-9JcBQRnPCXlWavYNyHdv_A==/lib/arm64/libkaldi_jni.so
2020-02-14 12:37:41.291 26351-26351/? A/DEBUG:     #02 pc 000000000069b260  /data/app/org.kaldi.demo-9JcBQRnPCXlWavYNyHdv_A==/lib/arm64/libkaldi_jni.so
2020-02-14 12:37:41.291 26351-26351/? A/DEBUG:     #03 pc 000000000069829c  /data/app/org.kaldi.demo-9JcBQRnPCXlWavYNyHdv_A==/lib/arm64/libkaldi_jni.so
2020-02-14 12:37:41.291 26351-26351/? A/DEBUG:     #04 pc 00000000006979a0  /data/app/org.kaldi.demo-9JcBQRnPCXlWavYNyHdv_A==/lib/arm64/libkaldi_jni.so
2020-02-14 12:37:41.291 26351-26351/? A/DEBUG:     #05 pc 0000000000697920  /data/app/org.kaldi.demo-9JcBQRnPCXlWavYNyHdv_A==/lib/arm64/libkaldi_jni.so (__cxa_throw+120)
2020-02-14 12:37:41.291 26351-26351/? A/DEBUG:     #06 pc 0000000000240644  /data/app/org.kaldi.demo-9JcBQRnPCXlWavYNyHdv_A==/lib/arm64/libkaldi_jni.so (kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)+112)
2020-02-14 12:37:41.291 26351-26351/? A/DEBUG:     #07 pc 00000000005c98cc  /data/app/org.kaldi.demo-9JcBQRnPCXlWavYNyHdv_A==/lib/arm64/libkaldi_jni.so (kaldi::ParseOptions::ReadConfigFile(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+1200)
2020-02-14 12:37:41.291 26351-26351/? A/DEBUG:     #08 pc 000000000029f418  /data/app/org.kaldi.demo-9JcBQRnPCXlWavYNyHdv_A==/lib/arm64/libkaldi_jni.so (_ZN5kaldi18ReadConfigFromFileINS_19OnlineSpliceOptionsEEEvRKNSt6__ndk112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEPT_+364)
2020-02-14 12:37:41.291 26351-26351/? A/DEBUG:     #09 pc 000000000029b1ac  /data/app/org.kaldi.demo-9JcBQRnPCXlWavYNyHdv_A==/lib/arm64/libkaldi_jni.so (kaldi::OnlineIvectorExtractionInfo::Init(kaldi::OnlineIvectorExtractionConfig const&)+480)
2020-02-14 12:37:41.291 26351-26351/? A/DEBUG:     #10 pc 0000000000273fa8  /data/app/org.kaldi.demo-9JcBQRnPCXlWavYNyHdv_A==/lib/arm64/libkaldi_jni.so (Model::Model(char const*)+1512)
2020-02-14 12:37:41.292 26351-26351/? A/DEBUG:     #11 pc 0000000000240160  /data/app/org.kaldi.demo-9JcBQRnPCXlWavYNyHdv_A==/lib/arm64/libkaldi_jni.so (Java_org_kaldi_voskJNI_new_1Model+88)
2020-02-14 12:37:41.292 26351-26351/? A/DEBUG:     #12 pc 000000000000991c  /data/app/org.kaldi.demo-9JcBQRnPCXlWavYNyHdv_A==/oat/arm64/base.odex (offset 0x9000)
2020-02-14 12:37:41.608 26343-26343/? E/System: Unable to open boot classpath entry: /system/framework/OPCommonTelephony.jar
2020-02-14 12:37:41.608 26343-26343/? E/System: java.io.FileNotFoundException: File doesn't exist: /system/framework/OPCommonTelephony.jar
        at java.util.zip.ZipFile.<init>(ZipFile.java:212)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:160)
        at java.util.jar.JarFile.<init>(JarFile.java:97)
        at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:47)
        at java.lang.VMClassLoader.createBootClassPathUrlHandlers(VMClassLoader.java:49)
        at java.lang.VMClassLoader.<clinit>(VMClassLoader.java:32)
        at java.lang.BootClassLoader.findResource(ClassLoader.java:1360)
        at java.lang.BootClassLoader.getResource(ClassLoader.java:1406)
        at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:987)
        at java.lang.Class.getResourceAsStream(Class.java:2211)
        at java.util.logging.LogManager.readConfiguration(LogManager.java:1297)
        at java.util.logging.LogManager$3.run(LogManager.java:390)
        at java.util.logging.LogManager$3.run(LogManager.java:388)
        at java.security.AccessController.doPrivileged(AccessController.java:69)
        at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:387)
        at java.util.logging.LogManager.-wrap5(Unknown Source:0)
        at java.util.logging.LogManager$2.run(LogManager.java:336)
        at java.security.AccessController.doPrivileged(AccessController.java:43)
        at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:329)
        at java.util.logging.LogManager.getLogManager(LogManager.java:369)
        at java.util.logging.Logger.demandLogger(Logger.java:449)
        at java.util.logging.Logger.getLogger(Logger.java:505)
        at android.icu.util.TimeZone.<clinit>(TimeZone.java:95)
        at java.util.TimeZone.setDefault(TimeZone.java:746)
        at com.android.internal.os.RuntimeInit.commonInit(RuntimeInit.java:155)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:279)
2020-02-14 12:37:41.862 26364-26364/? E/AEE_AED: Skipped - do not care third party apk
2020-02-14 12:37:41.865 611-611/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_03
2020-02-14 12:37:41.894 961-1044/? E/InputDispatcher: channel 'f90c3a8 org.kaldi.demo/org.kaldi.demo.KaldiActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-02-14 12:37:41.966 961-1810/? E/PowerHalWrapper: <amsBoostStop> duration: 6000ms
2020-02-14 12:37:42.350 26363-26363/? E/System: Unable to open boot classpath entry: /system/framework/OPCommonTelephony.jar
2020-02-14 12:37:42.351 26363-26363/? E/System: java.io.FileNotFoundException: File doesn't exist: /system/framework/OPCommonTelephony.jar
        at java.util.zip.ZipFile.<init>(ZipFile.java:212)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:160)
        at java.util.jar.JarFile.<init>(JarFile.java:97)
        at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:47)
        at java.lang.VMClassLoader.createBootClassPathUrlHandlers(VMClassLoader.java:49)
        at java.lang.VMClassLoader.<clinit>(VMClassLoader.java:32)
        at java.lang.BootClassLoader.findResource(ClassLoader.java:1360)
        at java.lang.BootClassLoader.getResource(ClassLoader.java:1406)
        at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:987)
        at java.lang.Class.getResourceAsStream(Class.java:2211)
        at java.util.logging.LogManager.readConfiguration(LogManager.java:1297)
        at java.util.logging.LogManager$3.run(LogManager.java:390)
        at java.util.logging.LogManager$3.run(LogManager.java:388)
        at java.security.AccessController.doPrivileged(AccessController.java:69)
        at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:387)
        at java.util.logging.LogManager.-wrap5(Unknown Source:0)
        at java.util.logging.LogManager$2.run(LogManager.java:336)
        at java.security.AccessController.doPrivileged(AccessController.java:43)
        at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:329)
        at java.util.logging.LogManager.getLogManager(LogManager.java:369)
        at java.util.logging.Logger.demandLogger(Logger.java:449)
        at java.util.logging.Logger.getLogger(Logger.java:505)
        at android.icu.util.TimeZone.<clinit>(TimeZone.java:95)
        at java.util.TimeZone.setDefault(TimeZone.java:746)
        at com.android.internal.os.RuntimeInit.commonInit(RuntimeInit.java:155)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:279)
